// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/message.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MessageUploadCombine struct {
	Type_                string   `protobuf:"bytes,1,opt,name=type_,json=type,proto3" json:"type_,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageUploadCombine) Reset()         { *m = MessageUploadCombine{} }
func (m *MessageUploadCombine) String() string { return proto.CompactTextString(m) }
func (*MessageUploadCombine) ProtoMessage()    {}
func (*MessageUploadCombine) Descriptor() ([]byte, []int) {
	return fileDescriptor_33f3a5e1293a7bcd, []int{0}
}

func (m *MessageUploadCombine) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageUploadCombine.Unmarshal(m, b)
}
func (m *MessageUploadCombine) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageUploadCombine.Marshal(b, m, deterministic)
}
func (m *MessageUploadCombine) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageUploadCombine.Merge(m, src)
}
func (m *MessageUploadCombine) XXX_Size() int {
	return xxx_messageInfo_MessageUploadCombine.Size(m)
}
func (m *MessageUploadCombine) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageUploadCombine.DiscardUnknown(m)
}

var xxx_messageInfo_MessageUploadCombine proto.InternalMessageInfo

func (m *MessageUploadCombine) GetType_() string {
	if m != nil {
		return m.Type_
	}
	return ""
}

func (m *MessageUploadCombine) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MessageUploadCombine) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type ConfirmationFromNameNode struct {
	ValidMsg             bool     `protobuf:"varint,1,opt,name=validMsg,proto3" json:"validMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmationFromNameNode) Reset()         { *m = ConfirmationFromNameNode{} }
func (m *ConfirmationFromNameNode) String() string { return proto.CompactTextString(m) }
func (*ConfirmationFromNameNode) ProtoMessage()    {}
func (*ConfirmationFromNameNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_33f3a5e1293a7bcd, []int{1}
}

func (m *ConfirmationFromNameNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmationFromNameNode.Unmarshal(m, b)
}
func (m *ConfirmationFromNameNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmationFromNameNode.Marshal(b, m, deterministic)
}
func (m *ConfirmationFromNameNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmationFromNameNode.Merge(m, src)
}
func (m *ConfirmationFromNameNode) XXX_Size() int {
	return xxx_messageInfo_ConfirmationFromNameNode.Size(m)
}
func (m *ConfirmationFromNameNode) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmationFromNameNode.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmationFromNameNode proto.InternalMessageInfo

func (m *ConfirmationFromNameNode) GetValidMsg() bool {
	if m != nil {
		return m.ValidMsg
	}
	return false
}

type MessageUploadToDataNode struct {
	Type_                string   `protobuf:"bytes,1,opt,name=type_,json=type,proto3" json:"type_,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageUploadToDataNode) Reset()         { *m = MessageUploadToDataNode{} }
func (m *MessageUploadToDataNode) String() string { return proto.CompactTextString(m) }
func (*MessageUploadToDataNode) ProtoMessage()    {}
func (*MessageUploadToDataNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_33f3a5e1293a7bcd, []int{2}
}

func (m *MessageUploadToDataNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageUploadToDataNode.Unmarshal(m, b)
}
func (m *MessageUploadToDataNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageUploadToDataNode.Marshal(b, m, deterministic)
}
func (m *MessageUploadToDataNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageUploadToDataNode.Merge(m, src)
}
func (m *MessageUploadToDataNode) XXX_Size() int {
	return xxx_messageInfo_MessageUploadToDataNode.Size(m)
}
func (m *MessageUploadToDataNode) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageUploadToDataNode.DiscardUnknown(m)
}

var xxx_messageInfo_MessageUploadToDataNode proto.InternalMessageInfo

func (m *MessageUploadToDataNode) GetType_() string {
	if m != nil {
		return m.Type_
	}
	return ""
}

func (m *MessageUploadToDataNode) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MessageUploadToDataNode) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type ConfirmationFromDataNode struct {
	ValidMsg             bool     `protobuf:"varint,1,opt,name=validMsg,proto3" json:"validMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmationFromDataNode) Reset()         { *m = ConfirmationFromDataNode{} }
func (m *ConfirmationFromDataNode) String() string { return proto.CompactTextString(m) }
func (*ConfirmationFromDataNode) ProtoMessage()    {}
func (*ConfirmationFromDataNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_33f3a5e1293a7bcd, []int{3}
}

func (m *ConfirmationFromDataNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmationFromDataNode.Unmarshal(m, b)
}
func (m *ConfirmationFromDataNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmationFromDataNode.Marshal(b, m, deterministic)
}
func (m *ConfirmationFromDataNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmationFromDataNode.Merge(m, src)
}
func (m *ConfirmationFromDataNode) XXX_Size() int {
	return xxx_messageInfo_ConfirmationFromDataNode.Size(m)
}
func (m *ConfirmationFromDataNode) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmationFromDataNode.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmationFromDataNode proto.InternalMessageInfo

func (m *ConfirmationFromDataNode) GetValidMsg() bool {
	if m != nil {
		return m.ValidMsg
	}
	return false
}

//Rebels to nameNode
type CategorySelected struct {
	Category             string   `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CategorySelected) Reset()         { *m = CategorySelected{} }
func (m *CategorySelected) String() string { return proto.CompactTextString(m) }
func (*CategorySelected) ProtoMessage()    {}
func (*CategorySelected) Descriptor() ([]byte, []int) {
	return fileDescriptor_33f3a5e1293a7bcd, []int{4}
}

func (m *CategorySelected) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CategorySelected.Unmarshal(m, b)
}
func (m *CategorySelected) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CategorySelected.Marshal(b, m, deterministic)
}
func (m *CategorySelected) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CategorySelected.Merge(m, src)
}
func (m *CategorySelected) XXX_Size() int {
	return xxx_messageInfo_CategorySelected.Size(m)
}
func (m *CategorySelected) XXX_DiscardUnknown() {
	xxx_messageInfo_CategorySelected.DiscardUnknown(m)
}

var xxx_messageInfo_CategorySelected proto.InternalMessageInfo

func (m *CategorySelected) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

//nameNode to dataNode
type IdSelected struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IdSelected) Reset()         { *m = IdSelected{} }
func (m *IdSelected) String() string { return proto.CompactTextString(m) }
func (*IdSelected) ProtoMessage()    {}
func (*IdSelected) Descriptor() ([]byte, []int) {
	return fileDescriptor_33f3a5e1293a7bcd, []int{5}
}

func (m *IdSelected) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdSelected.Unmarshal(m, b)
}
func (m *IdSelected) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdSelected.Marshal(b, m, deterministic)
}
func (m *IdSelected) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdSelected.Merge(m, src)
}
func (m *IdSelected) XXX_Size() int {
	return xxx_messageInfo_IdSelected.Size(m)
}
func (m *IdSelected) XXX_DiscardUnknown() {
	xxx_messageInfo_IdSelected.DiscardUnknown(m)
}

var xxx_messageInfo_IdSelected proto.InternalMessageInfo

func (m *IdSelected) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

//dataNode to nameNode
type InfoById struct {
	IdData               string   `protobuf:"bytes,1,opt,name=id_data,json=idData,proto3" json:"id_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InfoById) Reset()         { *m = InfoById{} }
func (m *InfoById) String() string { return proto.CompactTextString(m) }
func (*InfoById) ProtoMessage()    {}
func (*InfoById) Descriptor() ([]byte, []int) {
	return fileDescriptor_33f3a5e1293a7bcd, []int{6}
}

func (m *InfoById) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfoById.Unmarshal(m, b)
}
func (m *InfoById) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfoById.Marshal(b, m, deterministic)
}
func (m *InfoById) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoById.Merge(m, src)
}
func (m *InfoById) XXX_Size() int {
	return xxx_messageInfo_InfoById.Size(m)
}
func (m *InfoById) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoById.DiscardUnknown(m)
}

var xxx_messageInfo_InfoById proto.InternalMessageInfo

func (m *InfoById) GetIdData() string {
	if m != nil {
		return m.IdData
	}
	return ""
}

//nameNode to Rebels
type DataFromOneCategory struct {
	IdData               []string `protobuf:"bytes,1,rep,name=id_data,json=idData,proto3" json:"id_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataFromOneCategory) Reset()         { *m = DataFromOneCategory{} }
func (m *DataFromOneCategory) String() string { return proto.CompactTextString(m) }
func (*DataFromOneCategory) ProtoMessage()    {}
func (*DataFromOneCategory) Descriptor() ([]byte, []int) {
	return fileDescriptor_33f3a5e1293a7bcd, []int{7}
}

func (m *DataFromOneCategory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataFromOneCategory.Unmarshal(m, b)
}
func (m *DataFromOneCategory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataFromOneCategory.Marshal(b, m, deterministic)
}
func (m *DataFromOneCategory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataFromOneCategory.Merge(m, src)
}
func (m *DataFromOneCategory) XXX_Size() int {
	return xxx_messageInfo_DataFromOneCategory.Size(m)
}
func (m *DataFromOneCategory) XXX_DiscardUnknown() {
	xxx_messageInfo_DataFromOneCategory.DiscardUnknown(m)
}

var xxx_messageInfo_DataFromOneCategory proto.InternalMessageInfo

func (m *DataFromOneCategory) GetIdData() []string {
	if m != nil {
		return m.IdData
	}
	return nil
}

func init() {
	proto.RegisterType((*MessageUploadCombine)(nil), "grpc.MessageUploadCombine")
	proto.RegisterType((*ConfirmationFromNameNode)(nil), "grpc.confirmationFromNameNode")
	proto.RegisterType((*MessageUploadToDataNode)(nil), "grpc.MessageUploadToDataNode")
	proto.RegisterType((*ConfirmationFromDataNode)(nil), "grpc.confirmationFromDataNode")
	proto.RegisterType((*CategorySelected)(nil), "grpc.CategorySelected")
	proto.RegisterType((*IdSelected)(nil), "grpc.idSelected")
	proto.RegisterType((*InfoById)(nil), "grpc.infoById")
	proto.RegisterType((*DataFromOneCategory)(nil), "grpc.dataFromOneCategory")
}

func init() { proto.RegisterFile("proto/message.proto", fileDescriptor_33f3a5e1293a7bcd) }

var fileDescriptor_33f3a5e1293a7bcd = []byte{
	// 400 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0xcf, 0xcb, 0xd3, 0x40,
	0x14, 0xa4, 0xf9, 0xea, 0x67, 0x7d, 0x60, 0x29, 0x5b, 0xb1, 0x31, 0xfe, 0x24, 0x7a, 0xf0, 0x62,
	0xa2, 0x15, 0xf4, 0x28, 0xb4, 0x45, 0x2c, 0xd8, 0x16, 0xd2, 0x7a, 0xf1, 0x52, 0x36, 0xbb, 0xaf,
	0x71, 0x21, 0xc9, 0x86, 0x64, 0x0d, 0xf4, 0xcf, 0xf3, 0x3f, 0x93, 0xdd, 0x4d, 0x13, 0x2a, 0xad,
	0xa7, 0xef, 0x94, 0xbc, 0xc9, 0xec, 0x64, 0xde, 0x0c, 0x0b, 0xe3, 0xa2, 0x94, 0x4a, 0x86, 0x19,
	0x56, 0x15, 0x4d, 0x30, 0x30, 0x13, 0xe9, 0x27, 0x65, 0xc1, 0xfc, 0x0d, 0x3c, 0x5a, 0x59, 0xf8,
	0x47, 0x91, 0x4a, 0xca, 0xe7, 0x32, 0x8b, 0x45, 0x8e, 0x64, 0x0c, 0xf7, 0xd4, 0xb1, 0xc0, 0xbd,
	0xdb, 0x7b, 0xd5, 0x7b, 0xfb, 0x20, 0xea, 0xeb, 0x81, 0x0c, 0xc1, 0x11, 0xdc, 0x75, 0x0c, 0xe2,
	0x08, 0x4e, 0x08, 0xf4, 0x39, 0x55, 0xd4, 0xbd, 0xb1, 0x1c, 0xfd, 0xee, 0x7f, 0x02, 0x97, 0xc9,
	0xfc, 0x20, 0xca, 0x8c, 0x2a, 0x21, 0xf3, 0xaf, 0xa5, 0xcc, 0xd6, 0x34, 0xc3, 0xb5, 0xe4, 0x48,
	0x3c, 0x18, 0xd4, 0x34, 0x15, 0x7c, 0x55, 0x25, 0x46, 0x77, 0x10, 0xb5, 0xb3, 0x1f, 0xc1, 0xe4,
	0xcc, 0xc8, 0x4e, 0x2e, 0xa8, 0xa2, 0xe6, 0xd8, 0x5d, 0x7a, 0x69, 0x45, 0xff, 0xe7, 0x25, 0x80,
	0xd1, 0x9c, 0x2a, 0x4c, 0x64, 0x79, 0xdc, 0x62, 0x8a, 0x4c, 0x21, 0xd7, 0x7c, 0xd6, 0x60, 0x8d,
	0x8f, 0x76, 0xf6, 0x9f, 0x01, 0x08, 0xde, 0x32, 0xad, 0xb3, 0xde, 0xc9, 0x99, 0xff, 0x1a, 0x06,
	0x22, 0x3f, 0xc8, 0xd9, 0x71, 0xc9, 0xc9, 0x04, 0xee, 0x0b, 0xbe, 0x37, 0x46, 0x2d, 0xe1, 0x56,
	0x70, 0x6d, 0xc9, 0x0f, 0x60, 0xac, 0x51, 0x6d, 0x71, 0x93, 0xe3, 0xe9, 0xef, 0xe7, 0xfc, 0x9b,
	0x8e, 0x3f, 0xfd, 0xe3, 0xc0, 0xb0, 0xc9, 0x6b, 0x8b, 0x65, 0x2d, 0x18, 0x92, 0x6f, 0x00, 0x4d,
	0x7b, 0xab, 0x2a, 0x21, 0x5e, 0xa0, 0xfb, 0x0d, 0x2e, 0x95, 0xeb, 0xbd, 0xb0, 0xdf, 0xae, 0xf6,
	0xb4, 0x86, 0x87, 0x5d, 0xfc, 0x5a, 0xec, 0xf9, 0x05, 0xb1, 0x8e, 0x71, 0x4d, 0xaf, 0xcd, 0x7a,
	0x07, 0x2f, 0x23, 0x64, 0x28, 0x6a, 0xec, 0x62, 0xcd, 0xcd, 0x1e, 0x3b, 0x19, 0x61, 0x8c, 0x69,
	0x45, 0x1e, 0x5b, 0x89, 0x7f, 0x63, 0xf7, 0x9e, 0x58, 0xfc, 0x52, 0x36, 0x5f, 0xe0, 0x69, 0xa3,
	0xba, 0xe4, 0x9d, 0x5e, 0xbb, 0xc4, 0xc8, 0x9e, 0xec, 0x8a, 0xf1, 0x86, 0x0d, 0xd2, 0x94, 0x31,
	0x7b, 0xf3, 0xd3, 0x4f, 0x84, 0xfa, 0xf5, 0x3b, 0x0e, 0x98, 0xcc, 0xc2, 0xfa, 0x03, 0xfb, 0xfc,
	0xbe, 0x7c, 0xc7, 0xb1, 0x0e, 0xb7, 0x8b, 0xef, 0x34, 0x9e, 0x86, 0xe6, 0x9e, 0xc4, 0xb7, 0xe6,
	0xf1, 0xf1, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x47, 0x86, 0xf2, 0x3e, 0x45, 0x03, 0x00, 0x00,
}
