// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/message.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MessageUploadCombine struct {
	Type_                string   `protobuf:"bytes,1,opt,name=type_,json=type,proto3" json:"type_,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageUploadCombine) Reset()         { *m = MessageUploadCombine{} }
func (m *MessageUploadCombine) String() string { return proto.CompactTextString(m) }
func (*MessageUploadCombine) ProtoMessage()    {}
func (*MessageUploadCombine) Descriptor() ([]byte, []int) {
	return fileDescriptor_33f3a5e1293a7bcd, []int{0}
}

func (m *MessageUploadCombine) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageUploadCombine.Unmarshal(m, b)
}
func (m *MessageUploadCombine) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageUploadCombine.Marshal(b, m, deterministic)
}
func (m *MessageUploadCombine) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageUploadCombine.Merge(m, src)
}
func (m *MessageUploadCombine) XXX_Size() int {
	return xxx_messageInfo_MessageUploadCombine.Size(m)
}
func (m *MessageUploadCombine) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageUploadCombine.DiscardUnknown(m)
}

var xxx_messageInfo_MessageUploadCombine proto.InternalMessageInfo

func (m *MessageUploadCombine) GetType_() string {
	if m != nil {
		return m.Type_
	}
	return ""
}

func (m *MessageUploadCombine) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MessageUploadCombine) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type ConfirmationFromNameNode struct {
	ValidMsg             bool     `protobuf:"varint,1,opt,name=validMsg,proto3" json:"validMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmationFromNameNode) Reset()         { *m = ConfirmationFromNameNode{} }
func (m *ConfirmationFromNameNode) String() string { return proto.CompactTextString(m) }
func (*ConfirmationFromNameNode) ProtoMessage()    {}
func (*ConfirmationFromNameNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_33f3a5e1293a7bcd, []int{1}
}

func (m *ConfirmationFromNameNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmationFromNameNode.Unmarshal(m, b)
}
func (m *ConfirmationFromNameNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmationFromNameNode.Marshal(b, m, deterministic)
}
func (m *ConfirmationFromNameNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmationFromNameNode.Merge(m, src)
}
func (m *ConfirmationFromNameNode) XXX_Size() int {
	return xxx_messageInfo_ConfirmationFromNameNode.Size(m)
}
func (m *ConfirmationFromNameNode) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmationFromNameNode.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmationFromNameNode proto.InternalMessageInfo

func (m *ConfirmationFromNameNode) GetValidMsg() bool {
	if m != nil {
		return m.ValidMsg
	}
	return false
}

type MessageUploadToDataNode struct {
	Type_                string   `protobuf:"bytes,1,opt,name=type_,json=type,proto3" json:"type_,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageUploadToDataNode) Reset()         { *m = MessageUploadToDataNode{} }
func (m *MessageUploadToDataNode) String() string { return proto.CompactTextString(m) }
func (*MessageUploadToDataNode) ProtoMessage()    {}
func (*MessageUploadToDataNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_33f3a5e1293a7bcd, []int{2}
}

func (m *MessageUploadToDataNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageUploadToDataNode.Unmarshal(m, b)
}
func (m *MessageUploadToDataNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageUploadToDataNode.Marshal(b, m, deterministic)
}
func (m *MessageUploadToDataNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageUploadToDataNode.Merge(m, src)
}
func (m *MessageUploadToDataNode) XXX_Size() int {
	return xxx_messageInfo_MessageUploadToDataNode.Size(m)
}
func (m *MessageUploadToDataNode) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageUploadToDataNode.DiscardUnknown(m)
}

var xxx_messageInfo_MessageUploadToDataNode proto.InternalMessageInfo

func (m *MessageUploadToDataNode) GetType_() string {
	if m != nil {
		return m.Type_
	}
	return ""
}

func (m *MessageUploadToDataNode) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MessageUploadToDataNode) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type ConfirmationFromDataNode struct {
	ValidMsg             bool     `protobuf:"varint,1,opt,name=validMsg,proto3" json:"validMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmationFromDataNode) Reset()         { *m = ConfirmationFromDataNode{} }
func (m *ConfirmationFromDataNode) String() string { return proto.CompactTextString(m) }
func (*ConfirmationFromDataNode) ProtoMessage()    {}
func (*ConfirmationFromDataNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_33f3a5e1293a7bcd, []int{3}
}

func (m *ConfirmationFromDataNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmationFromDataNode.Unmarshal(m, b)
}
func (m *ConfirmationFromDataNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmationFromDataNode.Marshal(b, m, deterministic)
}
func (m *ConfirmationFromDataNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmationFromDataNode.Merge(m, src)
}
func (m *ConfirmationFromDataNode) XXX_Size() int {
	return xxx_messageInfo_ConfirmationFromDataNode.Size(m)
}
func (m *ConfirmationFromDataNode) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmationFromDataNode.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmationFromDataNode proto.InternalMessageInfo

func (m *ConfirmationFromDataNode) GetValidMsg() bool {
	if m != nil {
		return m.ValidMsg
	}
	return false
}

func init() {
	proto.RegisterType((*MessageUploadCombine)(nil), "grpc.MessageUploadCombine")
	proto.RegisterType((*ConfirmationFromNameNode)(nil), "grpc.confirmationFromNameNode")
	proto.RegisterType((*MessageUploadToDataNode)(nil), "grpc.MessageUploadToDataNode")
	proto.RegisterType((*ConfirmationFromDataNode)(nil), "grpc.confirmationFromDataNode")
}

func init() { proto.RegisterFile("proto/message.proto", fileDescriptor_33f3a5e1293a7bcd) }

var fileDescriptor_33f3a5e1293a7bcd = []byte{
	// 276 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x91, 0xc1, 0x4b, 0xc3, 0x30,
	0x14, 0xc6, 0x59, 0xad, 0x32, 0x1f, 0xb8, 0x43, 0x26, 0x58, 0x0a, 0x8a, 0x14, 0x0f, 0x5e, 0x6c,
	0x75, 0x82, 0xde, 0x75, 0x88, 0x07, 0x5b, 0xa1, 0xd3, 0x8b, 0x17, 0x79, 0x6d, 0x62, 0x0c, 0x2c,
	0x7d, 0x25, 0x8d, 0x05, 0xff, 0x25, 0xff, 0x4a, 0x69, 0x3a, 0x37, 0x84, 0xcd, 0x93, 0xa7, 0xe4,
	0x7b, 0xef, 0xe5, 0xc7, 0x97, 0xef, 0xc1, 0xb8, 0x36, 0x64, 0x29, 0xd1, 0xa2, 0x69, 0x50, 0x8a,
	0xd8, 0x29, 0xe6, 0x4b, 0x53, 0x97, 0xd1, 0x23, 0xec, 0xa7, 0x7d, 0xf9, 0xb9, 0x9e, 0x13, 0xf2,
	0x5b, 0xd2, 0x85, 0xaa, 0x04, 0x1b, 0xc3, 0xb6, 0xfd, 0xac, 0xc5, 0x6b, 0x30, 0x38, 0x1e, 0x9c,
	0xee, 0xe6, 0x7e, 0x27, 0xd8, 0x08, 0x3c, 0xc5, 0x03, 0xcf, 0x55, 0x3c, 0xc5, 0x19, 0x03, 0x9f,
	0xa3, 0xc5, 0x60, 0xab, 0x9f, 0xe9, 0xee, 0xd1, 0x15, 0x04, 0x25, 0x55, 0x6f, 0xca, 0x68, 0xb4,
	0x8a, 0xaa, 0x3b, 0x43, 0x3a, 0x43, 0x2d, 0x32, 0xe2, 0x82, 0x85, 0x30, 0x6c, 0x71, 0xae, 0x78,
	0xda, 0x48, 0xc7, 0x1d, 0xe6, 0x4b, 0x1d, 0xe5, 0x70, 0xf0, 0xcb, 0xc8, 0x13, 0x4d, 0xd1, 0xa2,
	0x7b, 0xf6, 0x9f, 0x5e, 0x96, 0xd0, 0x3f, 0xbc, 0x4c, 0xbe, 0x06, 0x30, 0x5a, 0x98, 0x99, 0x09,
	0xd3, 0xaa, 0x52, 0xb0, 0x7b, 0x80, 0x45, 0x34, 0x69, 0x23, 0x59, 0x18, 0x77, 0xe1, 0xc5, 0xeb,
	0x92, 0x0b, 0x8f, 0xfa, 0xde, 0xc6, 0x10, 0x32, 0xd8, 0x5b, 0xfd, 0xad, 0x83, 0x1d, 0xae, 0x81,
	0xad, 0x26, 0x36, 0xf1, 0x7e, 0xfa, 0x37, 0x27, 0x2f, 0x91, 0x54, 0xf6, 0xfd, 0xa3, 0x88, 0x4b,
	0xd2, 0x49, 0x7b, 0x51, 0x5e, 0x9f, 0x9b, 0x33, 0x2e, 0xda, 0x64, 0x36, 0x7d, 0xc0, 0x62, 0x92,
	0xb8, 0x6d, 0x17, 0x3b, 0xee, 0xb8, 0xfc, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xfc, 0x22, 0x4a, 0x5e,
	0x0b, 0x02, 0x00, 0x00,
}
